### ISSUE TITLE
Add WAI-ARIA in components

### ISSUE THREAD

**Issue by felipefialho** [felipefialho/css-components#14]

**Comment by stevenvachon** [comment]
Looks like you've already added this in. Which prompts a question:

If we have (from the [collapse example](http://www.felipefialho.com/css-components/#component-collapse))
```html
<input class="collapse-open" type="checkbox" id="collapse-1" aria-hidden="true" hidden />
```

... isn't `aria-hidden` redundant when accessibility software completely ignores hidden (`display:none`) elements?

**Comment by LFeh** [comment]
This will a good question. But I believe the que role of the aria-hidden is to hide the element for screen readers through the HTML, unrelated to the CSS.

This make sense?

**Comment by stevenvachon** [comment]
Yes, and that *is* the reason `aria-hidden` exists. But to use it along with `hidden` is redundant.

**Comment by LFeh** [comment]
Uhm, I never thought that way. I wanted see the @deividmarques opinion about this question.

**Comment by deividmarques** [comment]
@LFeh, really should not use the hidden attribute, only the aria.

**Comment by stevenvachon** [comment]
Why use `aria-hidden` at all when `hidden` achieves the goal of hiding the checkbox from view and from accessibility software? The checkbox is only for its checking functionality.

**Comment by deividmarques** [comment]
@stevenvachon and @LFeh in this component, it would be better not to have this aria. You agree?

**Comment by stevenvachon** [comment]
I'd say that none of the checkboxes and radio buttons in these CSS-only components would benefit from `aria-hidden` when `hidden` accomplishes all goals combined.

An addition might be to use `aria-expanded="true"` on the content that is hidden/shown. When such is hidden (via `visibility:hidden`), accessibility software ignores them anyway, so the expanded state won't be noticed until it's un-hidden.

**Comment by deividmarques** [comment]
I agree with you!

**Comment by stevenvachon** [comment]
+1

**Comment by LFeh** [comment]
Very good @stevenvachon. I agree with you.

Want me, to make this modification, or would you rather send a pull request?

**Comment by stevenvachon** [comment]
Might be better if you do it. I thought that I'd have the time, but have had so much to do.

**Comment by LFeh** [comment]
+1
