### ISSUE TITLE
Browser tests: Android 4.0

### ISSUE THREAD

**Issue by neysimoes** [felipefialho/css-components#34]
I used Sauce Labs to did this tests.
- Carrousel works fine, but without animation
  <img width="478" alt="captura de tela 2016-03-18 as 11 41 34" src="https://cloud.githubusercontent.com/assets/5016853/13881122/6c6e0890-ecfe-11e5-895c-d5a4b064c1ec.png">
- Collapse does not work.
  <img width="479" alt="captura de tela 2016-03-18 as 11 42 58" src="https://cloud.githubusercontent.com/assets/5016853/13881194/9da765b4-ecfe-11e5-9864-4e32e91503ef.png">
- Dropdown does not work.
  <img width="479" alt="captura de tela 2016-03-18 as 11 45 45" src="https://cloud.githubusercontent.com/assets/5016853/13881447/b51666d6-ecff-11e5-8173-aecf58c3257f.png">
- Dropdown with hover works fine (using tap)
  <img width="480" alt="captura de tela 2016-03-18 as 11 51 31" src="https://cloud.githubusercontent.com/assets/5016853/13881486/dba9737e-ecff-11e5-841f-66d998cd9f95.png">
- Modal does not work
  <img width="479" alt="captura de tela 2016-03-18 as 11 53 19" src="https://cloud.githubusercontent.com/assets/5016853/13881553/168e4488-ed00-11e5-9edb-963b6a36a288.png">
- Tab does not work
  <img width="480" alt="captura de tela 2016-03-18 as 11 54 36" src="https://cloud.githubusercontent.com/assets/5016853/13881596/4235e1fe-ed00-11e5-9ce8-0b94bec1bd58.png">
- Tooltip woks fine (using tap)
  <img width="481" alt="captura de tela 2016-03-18 as 11 56 21" src="https://cloud.githubusercontent.com/assets/5016853/13881666/823de6fc-ed00-11e5-8a6a-1bd9194ffd9c.png">

**Comment by LFeh** [comment]
Thanks @neysimoes, I'll make some adjusts later.
