### ISSUE TITLE
Tab.css/.zip issues

### ISSUE THREAD

**Issue by fjanon** [felipefialho/css-components#42]
It seems to me that the following should not be in the build/tab.css file:

@media (max-width: $screen-xs-max) {
}
@media (min-width: $screen-sm) {
}
@media (min-width: $screen-sm) {
}

There might be a typo as well here: "painel" > "panel"?

.tab-painel {
  display: inline-block;
  min-height: 150px;
}
.tab-painel .tab-open {

**Comment by felipefialho** [comment]
Thanks!
